# 1. Implementar los dos pasos de eliminacion de gaus simple (Eliminacion hacia adelante y sustitucion hacia atras)

# a) Eliminacion hacia adelante (Cualquier tamaño)

In [1]:
import math as mt
import numpy as np
print "Para este método el num de incognitas debe ser igual al numero de acuaciones."
tam=int(input("Digite el numero de ecuaciones:  "))
tam2=tam+1
matriz = np.array([[None] * (tam2) for i in range(tam)])
print "\nIngrese en orden las constantes de las ecuaciones..."
for e in range (tam):
    print "Ecuacion "+repr(e+1)+":"
    for f in range (tam2):
        a=float(input())
        matriz[e][f]=a
    print matriz[[e][0]:[e+1][0]],"\n"
#Eliminacion hacia adelante
for k in range (tam-1):
    for i in range (k+1,tam):
        factor=matriz[i][k]/matriz[k][k]
        for j in range (k,tam2):
            matriz[i][j]=(matriz[i][j]-(factor*matriz[k][j]))
print "\nLa matriz triangular resultante es:\n"
#print matriz
for e in range (tam):
    print (matriz[[e][0]:[e+1][0]])

Para este método el num de incognitas debe ser igual al numero de acuaciones.
Digite el numero de ecuaciones:  3

Ingrese en orden las constantes de las ecuaciones...
Ecuacion 1:
3
-0.1
-0.2
7.85
[[3.0 -0.1 -0.2 7.85]] 

Ecuacion 2:
0.1
7
-0.3
-19.3
[[0.1 7.0 -0.3 -19.3]] 

Ecuacion 3:
0.3
-0.2
10
71.4
[[0.3 -0.2 10.0 71.4]] 


La matriz triangular resultante es:

[[3.0 -0.1 -0.2 7.85]]
[[0.0 7.0033 -0.2933 -19.5617]]
[[0.0 0.0 10.012 70.0843]]



# b) Sustitucion hacia atrás

In [2]:
ntam=tam-1
xn=round(matriz[ntam][tam]/matriz[ntam][ntam],5)
x=[]
suma=0.0
for k in range (tam):
    x.append(0)
x[ntam]=xn
i=ntam-1
while(i>=0):
    suma=matriz[i][tam]
    j=i+1
    while(j<=ntam):
        suma=suma -matriz[i][j]*x[j]
        j=j+1
    x[i]=suma/matriz[i][i]
    i=i-1
for g in range(ntam+1):
    print "\nX"+repr(g+1)+"=",x[g]


X1= 3.000000376

X2= -2.50004872003

X3= 7.00003


# 2. Desarrollar los ejercicios  del 9.1 al 9.8 del chapra

# ...9.1. Escriba de manera matricial el conjunto siguiente de ecuaciones: [50 = 5*X3+2*X2]; [10–X1=X3]; [3*X2 + 8*X1 = 20]         y halle la transpuesta         


In [3]:
m=np.array([[0,2,5,50],[1,0,1,10],[8,3,0,20]])
tam=len(m)
print tam
m2=np.zeros((4, 3))  # Matriz de ceros
#matriz = np.array([[None] * (4) for i in range(4)])
print "Matriz de coeficientes=\n",m
for i in range(tam):
    for j in range(tam+1):
        m2[j][i] = m[i][j]
print "\nTranspuesta=\n",m2
#Tambien puedo usar:
#print np.transpose(m)

3
Matriz de coeficientes=
[[ 0  2  5 50]
 [ 1  0  1 10]
 [ 8  3  0 20]]

Transpuesta=
[[  0.   1.   8.]
 [  2.   0.   3.]
 [  5.   1.   0.]
 [ 50.  10.  20.]]


# 9.2. segun las matrices definidas (A, B, C ,D, E, F, G):

In [4]:
A=np.array([[4,7],[1,2],[5,6]])
B=np.array([[4,2,7],[1,2,7],[1,0,4]])
C=np.array([[3],[6],[1]])
D=np.array([[9,4,3,-6],[2,-1,7,5]])
E=np.array([[1,5,8],[7,2,3],[4,0,6]])
F=np.array([[3,0,1],[1,7,3]])
G=np.array([[7,6,4]])
print "A:\n",A,"\nB:\n",B,"\nC:\n",C,"\nD:\n",D,"\nE:\n",E,"\nF:\n",F,"\nG:\n",G
#print np.shape(D)

A:
[[4 7]
 [1 2]
 [5 6]] 
B:
[[4 2 7]
 [1 2 7]
 [1 0 4]] 
C:
[[3]
 [6]
 [1]] 
D:
[[ 9  4  3 -6]
 [ 2 -1  7  5]] 
E:
[[1 5 8]
 [7 2 3]
 [4 0 6]] 
F:
[[3 0 1]
 [1 7 3]] 
G:
[[7 6 4]]


# a)¿Cuales son las dimensiones de las matrices? 

# rta: respectivamente son: 3x2 , 3x3 , 3x1 , 2x4 , 3x3, 2x3, 1x3

# b)Identifique las matrices cuadrada, columna y renglón

# rta: cuadrada: B,E ... Columna=C ... Renglón= G

# c)¿Cuales son los valores de los elementos a12, b23, d32, e22, f12 y g12?

# rta: a12=7 ; b23=7 ; d32=no existe ; e22=2  ; f12=0  ; g12=6  .

In [5]:
f=int(input("Fila= "))
c=int(input("col= "))
print G[f][c]

Fila= 0
col= 1
6


# d) Ejecute las siguientes operaciones: 

# ...... 1) [E] + [B]

In [6]:
#Se suma punto a punto
SumaEB=E+B
print SumaEB 

[[ 5  7 15]
 [ 8  4 10]
 [ 5  0 10]]


# .....2) [A] + [F]  

In [7]:
import cv2
x,y=A.shape
xx,yy=F.shape
f=[x,xx]
c=[y,yy]
print f,c
RA=np.resize(A,(max(c),max(f)))
RF=np.resize(F,(max(c),max(f)))
SumaAF=RA+RF
print SumaAF

[3L, 2L] [2L, 3L]
[[ 7  7  2]
 [ 3 12  9]
 [ 7  7  2]]


# Rta: No se pueden sumar matrices de dimensiones diferentes

# .....3) [B] – [E] 

In [8]:
RestaBE=B-E
print RestaBE 

[[ 3 -3 -1]
 [-6  0  4]
 [-3  0 -2]]


# .....4) 7 × [B] 


In [9]:
Mul7B=7*B
print Mul7B 

[[28 14 49]
 [ 7 14 49]
 [ 7  0 28]]


# .....5) [E] × [B] 

In [10]:
MulEB=E*B
g=np.dot(E,B)
print "Producto punto E*B:\n",MulEB 
print "\nProducto Matricial:\n",g

Producto punto E*B:
[[ 4 10 56]
 [ 7  4 21]
 [ 4  0 24]]

Producto Matricial:
[[17 12 74]
 [33 18 75]
 [22  8 52]]


# ..... 6) {C}T 

In [11]:
print "Transpuesta de C:\n",np.transpose(C)

Transpuesta de C:
[[3 6 1]]


# ....7) [B] × [A] 

In [12]:
print np.dot(B,A)

[[53 74]
 [41 53]
 [24 31]]


# ....8) [D]T 

In [13]:
print np.transpose(D)

[[ 9  2]
 [ 4 -1]
 [ 3  7]
 [-6  5]]


# ....9) [A] × {C} 

In [14]:
RC=np.transpose(C) #{c} tupla? 
print A,"hhh"
print RC
print np.dot(A,RC)

[[4 7]
 [1 2]
 [5 6]] hhh
[[3 6 1]]


ValueError: shapes (3,2) and (1,3) not aligned: 2 (dim 1) != 1 (dim 0)

# rta: no se puede pues el numero de columnas de [A] no es igual al numero de filas de {C}

# ....10) [I] × [B] 

# rta: [I] inversa(?)

# ....11) [E]T [E]

In [ ]:
TE=np.transpose(E)
print np.dot(TE,E)

# ....12) {C}T {C}

In [ ]:
TC=np.transpose(C) #(?) Producto punto o matricial?
print np.dot(C,TC)

# 9.3.  Se definen tres matrices como sigue

In [ ]:
A=np.array([[1,6],[3,10],[7,4]])
B=np.array([[1,3],[0.5,2]])
C=np.array([[2,-2],[-3,1]])
print "A:\n",A,"\nB:\n",B,"\nC:\n",C

# a),b)y c) Ejecute todas las multiplicaciones que sea posible calcular entre parejas de las matrices, explique porqué no se pueden multiplicar entre las demas parejas y porqué es importante el orden de la multiplicacion

In [ ]:
AB=np.dot(A,B)
AC=np.dot(A,C)
BC=np.dot(B,C)
CB=np.dot(C,B)
print "A*B:\n",AB,"\nA*C:\n",AC,"\nB*C:\n",BC,"\nC*B:\n",CB

# Rta: No se puede multiplicar entre las demás parejas porque el numero de columnas de la primera matriz  multiplicar no es igual al numero de filas de la segunda; y es importante el orden como podemos ver B*C no es igual a C*B; pues para multiplicar dos matrices es necesario tomar el renglon de la primera y multiplicarlo punto a punto con la columna de la segunda,  luego sumar estos valores para obtener el primer valor de la matriz resultante; la multiplicacion matricial así no cumpliría la propiedad de conmutacion.

# 9.4 Use el método gráfico para resolver el sistema siguiente:  [4x1 – 8x2 = –24]; [x1 + 6x2 = 34] y Compruebe el resultado por medio de sustituirlo en las ecuaciones.

In [ ]:
matriz=np.array([[4.0,-8.0,-24.0],[1,6.0,34.0]]) #POner punto float
#Sustitucion dos ecuaciones con dos incognitas
#x2=(matriz[0][2]-matriz[0][0])/matriz[0][1]
x1=(matriz[1][2]-(matriz[1][1]*(matriz[0][2]/matriz[0][1])))/(matriz[1][0]-(matriz[1][1]*(matriz[0][0]/matriz[0][1])))
x2=(matriz[0][2]-(matriz[0][0]*x1))/matriz[0][1]
print "x1:",x1, "\nx2:",x2

# 9.5 Dado el sistema de ecuaciones siguiente [–1.1x1 + 10x2 = 120]; [–2x1 + 17.4x2 = 174]


# a)  Resuélvalo gráficamente y compruebe el resultado con la sustitución en las ecuaciones. 

In [25]:
#Sustitucion dos ecuaciones con dos incognitas
matriz=np.array([[-1.1,10,120],[-2,17.4,174]])
#x2=(matriz[0][2]-matriz[0][0])/matriz[0][1]
x1=(matriz[1][2]-(matriz[1][1]*(matriz[0][2]/matriz[0][1])))/(matriz[1][0]-(matriz[1][1]*(matriz[0][0]/matriz[0][1])))
x2=(matriz[0][2]-(matriz[0][0]*x1))/matriz[0][1]
print "x1:",x1, "\nx2:",x2

x1: 404.651162791 
x2: 56.511627907


# b)  Calcule el determinante. 

In [21]:
"""print "Este ejercicio es para tres ecuaciones\n"
tam=3
tam2=tam+1
a = np.array([[None] * (tam2) for i in range(tam)])
print "Ingrese en orden las constantes de las ecuaciones..."
for e in range (tam):
    print "Ecuacion "+repr(e+1)+":"
    for f in range (tam2):
        z=float(input())
        a[e][f]=z
    print a[[e][0]:[e+1][0]],"\n"
    
#Determinante
det=a[0][0]*((a[1][1]*a[2][2])-(a[1][2]*a[2][1]))-a[0][1]*((a[1][0]*a[2][2])-(a[1][2]*a[2][0]))+a[0][2]*((a[1][0]*a[2][1])-(a[1][1]*a[2][0]))
"""
a=np.array([[-1.1,10,120],[-2,17.4,174]])
det=a[0][0]*a[1][1]-a[0][1]*a[1][0]
print "Determinante:",det

Determinante: 0.86


# c)  Resuelva por medio de la eliminación de incógnitas

In [24]:
#Eliminacion de incognitas
a=np.array([[-1.1,10,120],[-2,17.4,174]])
x2=((a[0][0]*a[1][2])-(a[1][0]*a[0][2]))/((a[0][0]*a[1][1])-(a[0][1]*a[1][0]))
x1=((a[1][1]*a[0][2])-(a[0][1]*a[1][2]))/((a[0][0]*a[1][1])-(a[0][1]*a[1][0]))
print "X1:",x1,"\nX2:",x2

X1: 404.651162791 
X2: 56.511627907


In [43]:
matriz=np.array([[-1.1,10,120],[-2,17.4,174]])
tam=2
tam2=tam+1
for k in range (tam-1):
    for i in range (k+1,tam):
        factor=matriz[i][k]/matriz[k][k]
        for j in range (k,tam2):
            matriz[i][j]=round(matriz[i][j]-(factor*matriz[k][j]),4)
ntam=tam-1
xn=round(matriz[ntam][tam]/matriz[ntam][ntam],5)
x=[]
suma=0.0
for k in range (tam):
    x.append(0)
x[ntam]=xn
i=ntam-1
while(i>=0):
    suma=matriz[i][tam]
    j=i+1
    while(j<=ntam):
        suma=suma -matriz[i][j]*x[j]
        j=j+1
    x[i]=suma/matriz[i][i]
    i=i-1
for g in range(ntam+1):
    print "\nX"+repr(g+1)+"=",x[g]


X1= 404.662909091

X2= 56.51292


# 9.6 Para el sistema de ecuaciones que sigue         :  [2x2 + 5x3 = 9]; [2x1 + x2 + x3 = 9], [3x1 + x2 = 10]
 

# a)  Calcule el determinante.  

In [27]:
a=np.array([[0,2,5,9],[2,1,1,9],[3,1,0,10]])
#Determinante
det=a[0][0]*((a[1][1]*a[2][2])-(a[1][2]*a[2][1]))-a[0][1]*((a[1][0]*a[2][2])-(a[1][2]*a[2][0]))+a[0][2]*((a[1][0]*a[2][1])-(a[1][1]*a[2][0]))
print "Det:",det

Det: 1


# b)  Use la regla de Cramer para encontrar cuál es el valor de las x.

In [29]:
#solucion por cramer
x1=(a[0][3]*((a[1][1]*a[2][2])-(a[1][2]*a[2][1]))-a[0][1]*((a[1][3]*a[2][2])-(a[1][2]*a[2][3]))+a[0][2]*((a[1][3]*a[2][1])-(a[1][1]*a[2][3])))/det
x2=(a[0][0]*((a[1][3]*a[2][2])-(a[1][2]*a[2][3]))-a[0][3]*((a[1][0]*a[2][2])-(a[1][2]*a[2][0]))+a[0][2]*((a[1][0]*a[2][3])-(a[1][3]*a[2][0])))/det
x3=(a[0][0]*((a[1][1]*a[2][3])-(a[1][3]*a[2][1]))-a[0][1]*((a[1][0]*a[2][3])-(a[1][3]*a[2][0]))+a[0][3]*((a[1][0]*a[2][1])-(a[1][1]*a[2][0])))/det
print 'X1: ',x1, '\nx2: ',x2, '\nx3: ',x3

X1:  6 
x2:  -8 
x3:  5


# c)  Sustituya el resultado en las ecuaciones originales para efectos de comprobación.

In [37]:
#Comprobacion 
ec1=2*x2 + 5*x3 #9
ec2=2*x1 + x2 + x3 #9
ec3=3*x1 + x2 #10
print "Para ec1:",ec1,"\nPara ec2:",ec2,"\nPara ec3:",ec3

Para ec1: 9 
Para ec2: 9 
Para ec3: 10


# 9.7 Dadas las ec...  [0.5x1 – x2 = –9.5] ; [1.02x1 – 2x2 = –18.8]
 

# a)  Calcule el determinante. 

In [38]:
a=np.array([[0.5,-1,-9.5],[1.02,-2,-18.8]])
det=a[0][0]*a[1][1]-a[0][1]*a[1][0]
print "Determinante:",det

Determinante: 0.02


# b)  Resuelva por medio de la eliminación de incógnitas. 

In [39]:
a=np.array([[0.5,-1,-9.5],[1.02,-2,-18.8]])
x2=((a[0][0]*a[1][2])-(a[1][0]*a[0][2]))/((a[0][0]*a[1][1])-(a[0][1]*a[1][0]))
x1=((a[1][1]*a[0][2])-(a[0][1]*a[1][2]))/((a[0][0]*a[1][1])-(a[0][1]*a[1][0]))
print "X1:",x1,"\nX2:",x2

X1: 10.0 
X2: 14.5


# c)  Resuelva otra vez, pero modifique ligeramente el elemento a11 a 0.52. Interprete sus resultados. 

In [42]:
a=np.array([[0.52,-1,-9.5],[1.02,-2,-18.8]])
x2=((a[0][0]*a[1][2])-(a[1][0]*a[0][2]))/((a[0][0]*a[1][1])-(a[0][1]*a[1][0]))
x1=((a[1][1]*a[0][2])-(a[0][1]*a[1][2]))/((a[0][0]*a[1][1])-(a[0][1]*a[1][0]))
print "X1:",x1,"\nX2:",x2

X1: -10.0 
X2: 4.3


# rta: cualquier variacion en algun dato, por minima que parezca refeja una gran variacion en la solucion de un sistema de ecuaciones; podria considerarse que es un sistema mal condicionado, como la solucion se encuentra en la interseccion de las rectas, esto pasa porque las pendientes de las rectas estan muy cercanas, casi iguales (podemos ver que la determinante es casi cero, la matriz es casi singular).

# 9.8 Dadas las ecuaciones siguientes [10x1 + 2x2 – x3 = 27]; [–3x1 – 6x2 + 2x3 = –61.5]; [x1 + x2 + 5x3 = –21.5] 

# a)  Resuelva por eliminación de Gauss simple. Efectúe todos los pasos del cálculo.

In [49]:
matriz=np.array([[10,2,-1,27],[-3,-6,2,-61.5],[1,1,5,-21.5]])
tam=3
tam2=tam+1
for k in range (tam-1):
    for i in range (k+1,tam):
        factor=matriz[i][k]/matriz[k][k]
        for j in range (k,tam2):
            matriz[i][j]=round(matriz[i][j]-(factor*matriz[k][j]),4)
ntam=tam-1
xn=round(matriz[ntam][tam]/matriz[ntam][ntam],5)
x=[]
suma=0.0
for k in range (tam):
    x.append(0)
x[ntam]=xn
i=ntam-1
while(i>=0):
    suma=matriz[i][tam]
    j=i+1
    while(j<=ntam):
        suma=suma -matriz[i][j]*x[j]
        j=j+1
    x[i]=suma/matriz[i][i]
    i=i-1
for g in range(ntam+1):
    print "\nX"+repr(g+1)+"=",x[g]


X1= 0.500002222222

X2= 8.00001888889

X3= -5.99994


# b)  Sustituya los resultados en las ecuaciones originales a fin de comprobar sus respuestas.

In [50]:
ec1=10*x[0]+2*x[1]-x[2] # 27
ec2=-3*x[0]-6*x[1]+2*x[2] # –61.5
ec3=x[0]+x[1]+5*x[2] # –21.5
print "Para ec1:",ec1,"\nPara ec2:",ec2,"\nPara ec3:",ec3

Para ec1: 27.0 
Para ec2: -61.5 
Para ec3: -21.4996788889
