# 1. Implementar el pseudocódigo de la Figura 9.6, del método de eliminación de Gauss con pivoteo parcial.

In [29]:
#####PIVOTEO PARCIAL - CUALQUIER NUMERO DE ECUACIONES#####
import math as mt
import numpy as np
print "Para este método el num de incognitas debe ser igual al numero de acuaciones."
tam=int(input("Digite el numero de ecuaciones:  "))
tam2=tam+1
matriz = np.array([[None] * (tam2) for i in range(tam)])
print "\nIngrese en orden las constantes de las ecuaciones..."
for e in range (tam):
    print "Ecuacion "+repr(e+1)+":"
    for f in range (tam2):
        a=float(input())
        matriz[e][f]=a
    print matriz[[e][0]:[e+1][0]],"\n"
vaux=[]
indicef=0
print "Matriz de coeficiente:\n",matriz
for k in range (tam-1):
    #Seleccion del mayor pivote
    indicef=k#Indice fila del mayor
    for i in range (k+1,tam):
        if((abs(matriz[i][k]))>(abs(matriz[indicef][k]))):
            indicef=i
    #Intercambio si es necesario
    if(k!=indicef):
        vaux[:]=matriz[k,:] #asigna matriz pivote menor 
        matriz[k,:]=matriz[indicef,:]#asigna matriz pivote mayor
        matriz[indicef,:]=vaux[:] #al que antes tenia el pivote mayor, la deja en la posicion que tenia el del pivote menor
    for i in range (k+1,tam):
        factor=matriz[i][k]/matriz[k][k]
        for j in range (k,tam2):
            matriz[i][j]=(matriz[i][j]-(factor*matriz[k][j]))
    """for i in range (j+1,tam):
        matriz[j,:]=(matriz[i,:]+matriz[j,:])*(-matriz[i][j]/matriz[j][j])"""
print "matriz triangular resultante:\n", matriz
#######sustitucion hacia atras########
ntam=tam-1
xn=(matriz[ntam][tam]/matriz[ntam][ntam])
x=[]
suma=0.0
for k in range (tam):
    x.append(0)
x[ntam]=xn
i=ntam-1
while(i>=0):
    suma=matriz[i][tam]
    j=i+1
    while(j<=ntam):
        suma=suma -matriz[i][j]*x[j]
        j=j+1
    x[i]=suma/matriz[i][i]
    i=i-1
for g in range(ntam+1):
    print "\nX"+repr(g+1)+"=",x[g]

Para este método el num de incognitas debe ser igual al numero de acuaciones.
Digite el numero de ecuaciones:  3

Ingrese en orden las constantes de las ecuaciones...
Ecuacion 1:
3.9
6
7
8
[[3.9 6.0 7.0 8.0]] 

Ecuacion 2:
9
6.8
56
4
[[9.0 6.8 56.0 4.0]] 

Ecuacion 3:
5
23
4.8
6
[[5.0 23.0 4.8 6.0]] 

Matriz de coeficiente:
[[3.9 6.0 7.0 8.0]
 [9.0 6.8 56.0 4.0]
 [5.0 23.0 4.8 6.0]]
matriz triangular resultante:
[[9.0 6.8 56.0 4.0]
 [0.0 19.22222222222222 -26.311111111111114 3.7777777777777777]
 [-4.440892098500626e-16 0.0 -13.0873063583815 5.666589595375722]]

X1= 3.43786327837

X2= -0.3961302131

X3= -0.432983643861


# 2. Desarrollar los ejercicios 9.9 a 9.13 Pags. 280-281 [Chapra 2007]

# 9.9 Use la eliminación de Gauss para resolver el sistema que sigue: [8x1 + 2x2 – 2x3 = –2]; [10x1 + 2x2 + 4x3 = 4]; [12x1 + 2x2 + 2x3 = 6]

# Emplee pivoteo parcial y compruebe las respuestas sustituyéndolas en las ecuaciones originales.

In [30]:
def pivoteo_par(matriz,x):
    vaux=[]
    indicef=0
    tam=3
    tam2=tam+1
    print "Matriz de coeficiente:\n",matriz
    for k in range (tam-1):
        #Seleccion del mayor pivote
        indicef=k#Indice fila del mayor
        for i in range (k+1,tam):
            if((abs(matriz[i][k]))>(abs(matriz[indicef][k]))):
                indicef=i
        #Intercambio si es necesario
        if(k!=indicef):
            vaux[:]=matriz[k,:] #asigna matriz pivote menor 
            matriz[k,:]=matriz[indicef,:]#asigna matriz pivote mayor
            matriz[indicef,:]=vaux[:] #al que antes tenia el pivote mayor, la deja en la posicion que tenia el del pivote menor
        for i in range (k+1,tam):
            factor=matriz[i][k]/matriz[k][k]
            for j in range (k,tam2):
                matriz[i][j]=(matriz[i][j]-(factor*matriz[k][j]))
    print "matriz triangular resultante:\n", matriz
    #######sustitucion hacia atras########
    ntam=tam-1
    xn=(matriz[ntam][tam]/matriz[ntam][ntam])
    suma=0.0
    for k in range (tam):
        x.append(0)
    x[ntam]=xn
    i=ntam-1
    while(i>=0):
        suma=matriz[i][tam]
        j=i+1
        while(j<=ntam):
            suma=suma -matriz[i][j]*x[j]
            j=j+1
        x[i]=suma/matriz[i][i]
        i=i-1
    for g in range(ntam+1):
        print "\nX"+repr(g+1)+"=",x[g]
    return (x)
#####MAIN###
x=[]
matriz=np.array([[8.0,2,-2,-2],[10,2,4,4],[12.0,2,2,6]])
pivoteo_par(matriz,x)

Matriz de coeficiente:
[[  8.   2.  -2.  -2.]
 [ 10.   2.   4.   4.]
 [ 12.   2.   2.   6.]]
matriz triangular resultante:
[[ 12.           2.           2.           6.        ]
 [  0.           0.66666667  -3.33333333  -6.        ]
 [  0.           0.           4.           2.        ]]

X1= 1.5

X2= -6.5

X3= 0.5


[1.5, -6.5, 0.49999999999999989]

In [31]:
#comprobacion:
def comprobacion(matriz,x):
    ec1=matriz[0][0]*x[0]+matriz[0][1]*x[1]+matriz[0][2]*x[2]
    ec2=matriz[1][0]*x[0]+matriz[1][1]*x[1]+matriz[1][2]*x[2]
    ec3=matriz[2][0]*x[0]+matriz[2][1]*x[1]+matriz[2][2]*x[2] 
    print "Para ec1:",ec1,"\nPara ec2:",ec2,"\nPara ec3:",ec3
    
matriz=np.array([[8.0,2,-2,-2],[10,2,4,4],[12.0,2,2,6]])
comprobacion(matriz,x)

Para ec1: -2.0 
Para ec2: 4.0 
Para ec3: 6.0


# 9.10 Dado el sistema siguiente de ecuaciones [–3x2 + 7x3 = 2]; [x1 + 2x2 – x3 = 3]; [5x1 – 2x2 = 2]
 

# a)  Calcule el determinante. 

In [32]:
a=np.array([[0,-3.0,7,2],[1,2,-1,3],[5.0,-2,0,2]])
#Determinante
det=a[0][0]*((a[1][1]*a[2][2])-(a[1][2]*a[2][1]))-a[0][1]*((a[1][0]*a[2][2])-(a[1][2]*a[2][0]))+a[0][2]*((a[1][0]*a[2][1])-(a[1][1]*a[2][0]))
print "Det:",det

Det: -69.0


# b)  Use la regla de Cramer para encontrar cuáles son los valores de las x.

In [33]:
#solucion por cramer
x1=(a[0][3]*((a[1][1]*a[2][2])-(a[1][2]*a[2][1]))-a[0][1]*((a[1][3]*a[2][2])-(a[1][2]*a[2][3]))+a[0][2]*((a[1][3]*a[2][1])-(a[1][1]*a[2][3])))/det
x2=(a[0][0]*((a[1][3]*a[2][2])-(a[1][2]*a[2][3]))-a[0][3]*((a[1][0]*a[2][2])-(a[1][2]*a[2][0]))+a[0][2]*((a[1][0]*a[2][3])-(a[1][3]*a[2][0])))/det
x3=(a[0][0]*((a[1][1]*a[2][3])-(a[1][3]*a[2][1]))-a[0][1]*((a[1][0]*a[2][3])-(a[1][3]*a[2][0]))+a[0][3]*((a[1][0]*a[2][1])-(a[1][1]*a[2][0])))/det
print 'X1: ',x1, '\nx2: ',x2, '\nx3: ',x3

X1:  0.985507246377 
x2:  1.46376811594 
x3:  0.913043478261


# c)  Emplee la eliminación de Gauss con pivoteo parcial para obtener cuáles serían los valores de las x.

In [34]:
matriz=np.array([[0,-3.0,7,2],[1,2,-1,3],[5.0,-2,0,2]])
pivoteo_par(matriz,x)

Matriz de coeficiente:
[[ 0. -3.  7.  2.]
 [ 1.  2. -1.  3.]
 [ 5. -2.  0.  2.]]
matriz triangular resultante:
[[ 5.  -2.   0.   2. ]
 [ 0.  -3.   7.   2. ]
 [ 0.   0.   4.6  4.2]]

X1= 0.985507246377

X2= 1.46376811594

X3= 0.913043478261


[0.98550724637681175, 1.4637681159420293, 0.91304347826086962, 0, 0, 0]

# d)  Sustituya sus resultados en las ecuaciones originales para efectos de comprobación.

In [35]:
matriz=np.array([[0,-3.0,7,2],[1,2,-1,3],[5.0,-2,0,2]])
comprobacion(matriz,x)

Para ec1: 2.0 
Para ec2: 3.0 
Para ec3: 2.0


# 9.11 Dadas las ecuaciones [2x1 – 6x2 – x3 = –38]; [–3x1 – x2 + 7x3 = –34]; [–8x1 + x2 – 2x3 = –20]

# a)  Resuelva por eliminación de Gauss con pivoteo parcial. Efectúe todos los pasos del cálculo. 

In [36]:
matriz=np.array([[2,-6.0,-1,-38],[-3,-1,7,-34],[-8.0,1,-2,-20]])
pivoteo_par(matriz,x)

Matriz de coeficiente:
[[  2.  -6.  -1. -38.]
 [ -3.  -1.   7. -34.]
 [ -8.   1.  -2. -20.]]
matriz triangular resultante:
[[ -8.           1.          -2.         -20.        ]
 [  0.          -5.75        -1.5        -43.        ]
 [  0.           0.           8.10869565 -16.2173913 ]]

X1= 4.0

X2= 8.0

X3= -2.0


[4.0, 8.0, -2.0, 0, 0, 0, 0, 0, 0]

# b)  Sustituya los resultados en las ecuaciones originales para comprobar sus respuestas. 

In [37]:
matriz=np.array([[2,-6.0,-1,-38],[-3,-1,7,-34],[-8.0,1,-2,-20]])
comprobacion(matriz,x)

Para ec1: -38.0 
Para ec2: -34.0 
Para ec3: -20.0


# 9.12 Emplee la eliminación de Gauss-Jordan para resolver el sistema siguiente: 2x1 + x2 – x3 = 1 5x1 + 2x2 + 2x3 = –4 3x1 + x2 + x3 = 5

# No utilice pivoteo. Compruebe sus respuestas con la sustitución en las ecuaciones originales. 

In [38]:
import numpy as np
def gauss_jordan(m):
    (h,w)=(len(m),len(m[0]))
    c=0.0
    for y in range(0,h):
        #maxfila=y
        """for y2 in range(y+1, h):    #pivoteo
            if (abs(m[y2][y])>abs(m[maxfila][y])):
                maxfila=y2
        (m[y], m[maxfila]) = (m[maxfila], m[y])"""
        for y2 in range(y+1,h):    # Elimina columna y
            c = m[y2][y]/m[y][y]
            for x in range(y,w):
                m[y2][x]-=m[y][x]*c
    for y in range(h-1,-1,-1): 
        c=m[y][y]
        for y2 in range(0,y):
            for x in range(w-1,y-1,-1):
                m[y2][x]-=m[y][x]*m[y2][y]/c
        m[y][y]/=c
        for x in range(h,w):       # Normaliza la fila y
            m[y][x]/=c
    return m
matriz=np.array([[2.0,1,-1,1],[5,2,2,-4],[3,1.0,1,5.0]])
print gauss_jordan(matriz)
x=[]
for i in range (tam):
    x.append(m[i][tam])
for g in range(tam):
    print "\nX"+repr(g+1)+"=",x[g]


[[  1.   0.   0.  14.]
 [  0.   1.   0. -32.]
 [  0.   0.   1.  -5.]]

X1= 14.0

X2= -32.0

X3= -5.0


In [24]:
matriz=np.array([[2.0,1,-1,1],[5,2,2,-4],[3,1.0,1,5.0]])
print "\nComprobacion:\n"
comprobacion(matriz,x)


Comprobacion:

Para ec1: 1.0 
Para ec2: -4.0 
Para ec3: 5.0


# 9.13 Resuelva el sistema: x1 + x2 – x3 = –3 6x1 + 2x2 + 2x3 = 2 –3x1 + 4x2 + x3 = 1 por medio de  

# a) eliminación de Gauss simple

In [11]:
import numpy as np
matriz=np.array([[1,1.0,-1,-3],[-3,2,2,2.0],[-3,4,1,1]])
tam=3
tam2=tam+1
for k in range (tam-1):
    for i in range (k+1,tam):
        factor=matriz[i][k]/matriz[k][k]
        for j in range (k,tam2):
            matriz[i][j]=(matriz[i][j]-(factor*matriz[k][j]))
ntam=tam-1
xn=round(matriz[ntam][tam]/matriz[ntam][ntam],5)
x=[]
suma=0.0
for k in range (tam):
    x.append(0)
x[ntam]=xn
i=ntam-1
while(i>=0):
    suma=matriz[i][tam]
    j=i+1
    while(j<=ntam):
        suma=suma -matriz[i][j]*x[j]
        j=j+1
    x[i]=suma/matriz[i][i]
    i=i-1
for g in range(ntam+1):
    print "\nX"+repr(g+1)+"=",x[g]


X1= -4.0

X2= -2.0

X3= -3.0


# b) eliminación de Gauss con pivoteo parcial 

In [12]:
matriz=np.array([[1,1.0,-1,-3],[-3,2,2.0,2],[-3,4.0,1,1]])
pivoteo_par(matriz,x)

Matriz de coeficiente:
[[ 1.  1. -1. -3.]
 [-3.  2.  2.  2.]
 [-3.  4.  1.  1.]]
matriz triangular resultante:
[[-3.   2.   2.   2. ]
 [ 0.   2.  -1.  -1. ]
 [ 0.   0.   0.5 -1.5]]

X1= -4.0

X2= -2.0

X3= -3.0


[-4.0000000000000009, -2.0000000000000009, -3.0000000000000013, 0, 0, 0]

# c) método de Gauss-Jordan sin pivoteo parcial.

In [39]:
m=np.array([[1,1.0,-1,-3],[-3,2,2,2.0],[-3,4,1,1]])
tam=3
print gauss_jordan(m)
x=[]
for i in range (tam):
    x.append(m[i][tam])
for g in range(tam):
    print "\nX"+repr(g+1)+"=",x[g]

[[ 1.  0.  0. -4.]
 [ 0.  1.  0. -2.]
 [ 0.  0.  1. -3.]]

X1= -4.0

X2= -2.0

X3= -3.0
